@startuml ludo



class GameEngine{
    -turn = int  
    -borad = Board
    -players = Collection<Player
    -void nextPlayer()
    +void movePiece(int)
    -boolean legalMove(int)
    +void rollDice()

}

class Player {

    -piecesLocation = ArrayList<int>
    -
}


class Board{
    -boardState = ArrayList<int>
    -g
    +void empty
}

GameEngine -> Board : Contains 

class empty{
    
}


@enduml